name: CI Pipeline

on: 
  pull_request:
    branches:
      - devel
      - stage
      - prod 

jobs:
  validate-pr-source:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.validate.outputs.valid }}
    steps:
      - name: Validte PR source
        id: validate
        run: |
          BASE="${{ github.base_ref }}" # TARGET
          HEAD="${{ github.head_ref }}" # SOURCE

          if [[ "$BASE" == "devel" && "$HEAD" == feature/* ]]; then
            echo "Valid PR from $HEAD into $BASE"
            echo "valid=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ "$BASE" == "stage" && "$HEAD" == "devel" ]]; then
            echo "Valid PR from $HEAD into $BASE"
            echo "valid=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ "$BASE" == "prod" && "$HEAD" == "stage" ]]; then
            echo "Valid PR from $HEAD into $BASE"
            echo "valid=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ "$BASE" == "devel" && "$HEAD" == "main" ]]; then
            echo "Valid PR from $HEAD into $BASE"
            echo "valid=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Invalid PR from $HEAD into $BASE"
          echo "valid=false" >> $GITHUB_OUTPUT
          exit 1

  build:
    runs-on: ubuntu-latest
    needs: validate-pr-source
    if: needs.validate-pr-source.outputs.valid == 'true'
    steps: 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run formatter
        run: npm run prettier

      - name: Run tests
        env: 
          CI: true
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Upload Artifact build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: app/codebase/rdicidr-0.1.0


